#!/bin/bash

PWD=`pwd`
BACKEND_PROC=`sudo netstat -tulnp 2>/dev/null | grep :5005 | egrep -o "[0-9]+\/python3" | sed -e 's/\/.*//'`
if [[ $BACKEND_PROC ]]; then
	sudo kill "$BACKEND_PROC"
	echo "Flask app stopped."
fi

readonly venv="./.pms-backend-env/bin/activate"
PMS_SECRET_KEY="\xe4\x0c\x91\xd8\xc3\xa6\xb4\x17N\x83\xb3n\xb8I[\x9b0\x18V\x08,\x98\xcc8"
FLASK_APP=backend
FLASK_DEBUG=1

echo "Starting Flask..."
gnome-terminal --working-directory="$PWD/backend" --command=\
"bash -c 'source ${venv};\
export PMS_SECRET_KEY=${PMS_SECRET_KEY};\
export FLASK_APP=${FLASK_APP};\
export FLASK_DEBUG=${FLASK_DEBUG};\
flask run --port 5005'" 2>/dev/null

exec bash





	



